// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Product struct {
	ID          uuid.UUID
	ProductName string
	Description sql.NullString
	Brand       sql.NullString
	ProductCode string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type ProductScanned struct {
	ID        uuid.UUID
	ProductID uuid.UUID
	UserID    uuid.UUID
	Quantity  int32
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Email     string
	Password  string
}
